### ISSUE TITLE
NoSuchMethodError: The getter 'listeners' was called on null

### ISSUE THREAD

**Issue by RegNex** [LanarsInc/direct-select-flutter#9]
I get this error when integrating your plugin. The implementation was exactly as the example provided.

`int categoryPosition = 0;`

   ```
 List<String> _categories = [  "Breakfast1",
  "Breakfast2",
  "Lunch1",
  "Lunch2",
  "Dinner1",
  "Dinner2",];
```

   ```
DirectSelectItem<String> getDropDownMenuItem(String value) {
    return DirectSelectItem<String>(
        itemHeight: 56,
        value: value,
        itemBuilder: (context, value) {
          return Text(value);
        });
  }
```

 ```
 _getDslDecoration() {
    return BoxDecoration(
      border: BorderDirectional(
        bottom: BorderSide(width: 1, color: Colors.black12),
        top: BorderSide(width: 1, color: Colors.black12),
      ),
    );
  }
```

```
Row(
                              children: <Widget>[
                                DirectSelectList<String>(
                                    values: _categories,
                                    defaultItemIndex: categoryPosition,
                                    itemBuilder: (String value) =>
                                        getDropDownMenuItem(value),
                                    focusedItemDecoration: _getDslDecoration(),
                                    onItemSelectedListener: (item, index, context) {
                                      setState(() {
                                        categoryPosition = index;
                                      });
                                      Scaffold.of(context).showSnackBar(
                                          SnackBar(content: Text(item)));
                                    }),
                                    Padding(
                                    padding: EdgeInsets.only(right: 8),
                                      child: Icon(
      Icons.unfold_more,
      color: Colors.black,
    ),
                                    )
                              ],
                            ),`

```

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(375.0,
flutter: 812.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
flutter: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
flutter: false, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText:
flutter: false)):
flutter: The getter 'listeners' was called on null.
flutter: Receiver: null
flutter: Tried calling: listeners
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
flutter: #1      DirectSelectContainer.of (package:direct_select_flutter/direct_select_container.dart:89:10)
flutter: #2      DirectSelectState.didChangeDependencies (package:direct_select_flutter/direct_select_list.dart:122:46)
flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #13     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #41     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #114    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #132    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #158    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #162    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #168    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #181    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #185    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #187    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #189    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #193    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #194    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #198    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #200    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #201    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #210    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #218    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #220    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #222    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #223    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #225    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #227    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #232    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #233    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4875:32)
flutter: #234    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
flutter: #235    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #236    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
flutter: #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #239    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #240    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #244    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #245    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
flutter: #246    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #247    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #248    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #250    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #251    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #252    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #253    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #255    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #256    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #258    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #259    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
flutter: #260    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #261    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #262    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #263    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #264    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #268    _invoke (dart:ui/hooks.dart:236:10)
flutter: #269    _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'listeners' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'listeners' was called on null.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4363 pos 14: '_dependents.isEmpty': is not true.
```

**Comment by iyatsouba** [comment]
Hi @RegNex your DirectSelectList is must be wrapped with DirectSelectContainer. Please view example again)
